CC=tcc
CFLAGS= -I./win32/include -L./win32/lib

all: fps_counter rotate_cube windows_icon

fps_counter:
	$(CC) $(CFLAGS) fps_counter.c -lglfw3 -lopengl32 -o fps_counter.exe

rotate_cube:
	$(CC) $(CFLAGS) rotate_cube.c -lglfw3 -lopengl32 -o rotate_cube.exe

windows_icon: icon.o
	$(CC) $(CFLAGS) windows_icon.c icon.o -lglfw3 -lopengl32 -o windows_icon.exe

icon.o:
	windres -O coff win32/icon/resource.rc -o icon.o

clean:
	del *.o
	del *.exe
